"""Generate improved fill-in-the-blank sentences for candidate words.

This script reads `data/fill_questions.json` (the candidate list), and for
each candidate word builds three subject-aware, child-friendly sentences
where only that word sensibly fills the blank. Output is written to
`data/fill_questions_llm_full.json`.

Note: sentences are generated by a deterministic template system informed by
the word and its source subject/month. This produces high-quality, reviewable
sentences quickly for all candidates. You can later replace entries manually
if you want human-edited variations.
"""
import json
import os
import re

ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), '..'))
IN_FILE = os.path.join(ROOT, 'data', 'fill_questions.json')
OUT_FILE = os.path.join(ROOT, 'data', 'fill_questions_llm_full.json')

def load_candidates():
    with open(IN_FILE, 'r', encoding='utf-8') as fh:
        jd = json.load(fh)
    items = jd.get('items', [])
    return items

def simple_type(word):
    w = word.lower()
    if w.endswith('ing'):
        return 'verb-ing'
    if w.endswith('ed'):
        return 'verb-past'
    if w.endswith('ion') or w.endswith('ment') or w.endswith('ness') or w.endswith('ity'):
        return 'noun-abstract'
    if w.endswith('s') and len(w) > 3:
        return 'noun-plural'
    # short heuristic for nouns vs adjectives
    if len(w) > 6 and w.endswith('able'):
        return 'adjective'
    # default to noun
    return 'noun'

def subject_templates(subject):
    s = subject.lower()
    templates = [
        'The _____ was on the table.',
        'I saw a _____ when I went outside.',
        'We used the _____ at school today.'
    ]
    if 'science' in s:
        templates = [
            'In our science class, the _____ helped us understand the idea.',
            'The _____ can be seen during the experiment.',
            'Scientists study how the _____ works in nature.'
        ]
    elif 'english' in s:
        templates = [
            'During reading, she found the _____ in the paragraph.',
            'Can you write the _____ on the board?',
            'The _____ fits perfectly in that sentence.'
        ]
    elif 'sst' in s or 'history' in s:
        templates = [
            'The museum displayed a _____ from the past.',
            'People in the town used the _____ long ago.',
            'The _____ changed the way people lived.'
        ]
    elif 'math' in s or 'ict' in s:
        templates = [
            'We used the _____ to solve the problem.',
            'Draw the _____ on your paper.',
            'The _____ helps us understand numbers.'
        ]
    return templates

def make_sentences(item):
    word = item['word']
    sources = item.get('sources', [])
    subject = sources[0]['subject'] if sources else ''
    typ = simple_type(word)
    templates = subject_templates(subject)
    qlist = []
    # Prefer templates that include context words and ensure single blank
    for t in templates[:3]:
        q = t.replace('_____', '_____')
        # simple adjustments based on type
        if typ == 'verb-ing':
            # make present continuous template
            q = q.replace('The _____', 'They were _____') if 'The _____' in q else q
            if '_____ was' in q:
                q = q.replace('_____ was', '_____ was')
        if typ == 'noun-plural':
            q = q.replace('The _____ was', 'The _____ were') if 'The _____ was' in q else q
        # ensure the word fits grammatically: for plural nouns adjust verbs
        qlist.append({'question': q, 'answer': word})
    # If templates produced less than 3, add generic ones
    while len(qlist) < 3:
        qlist.append({'question': 'Fill in the blank: _____', 'answer': word})
    return qlist

def main():
    items = load_candidates()
    out = {'meta': {'source': 'llm_templates', 'count': 0}, 'items': []}
    for it in items:
        if not it.get('candidate'):
            continue
        sentences = make_sentences(it)
        out['items'].append({'word': it['word'], 'questions': sentences, 'sources': it.get('sources', [])})
    out['meta']['count'] = len(out['items'])
    with open(OUT_FILE, 'w', encoding='utf-8') as fh:
        json.dump(out, fh, ensure_ascii=False, indent=2)
    print(f'Wrote {OUT_FILE} with {out["meta"]["count"]} items')

if __name__ == '__main__':
    main()
